[build]
  command = ""
  publish = "guapulo-rsvp-website"
  functions = "guapulo-rsvp-website/netlify/functions"
  environment = { NODE_VERSION = "18" }

[forms]
  enabled = true

# Redirects and headers are managed inside the site folder's netlify.toml
