#!/usr/bin/env node
/**
 * build.js — Generates the deployable site files from _data/event-config.json
 *
 * Runs on every Netlify deploy (see netlify.toml build command).
 *
 * Generates:
 *   - index.html            (from templates/index.template.html)
 *   - success.html          (from templates/success.template.html)
 *   - generated-config.js   (countdown date etc. consumed by script.js)
 *   - build-info.json       (config hash — used by /admin to detect when a publish is live)
 *
 * DO NOT edit index.html / success.html directly — edit the templates.
 * DO NOT edit event data in code — edit _data/event-config.json (or use /admin).
 */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { deriveEventInfo } = require('./lib/event-derive');

const ROOT = __dirname;

// ---------------------------------------------------------------------------
// Load config
// ---------------------------------------------------------------------------
const configPath = path.join(ROOT, '_data', 'event-config.json');
const rawConfig = fs.readFileSync(configPath, 'utf8');
const config = JSON.parse(rawConfig);
const derived = deriveEventInfo(config);

// ---------------------------------------------------------------------------
// Template values
// ---------------------------------------------------------------------------
function escapeHtml(str) {
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

const eventName = config.event.name;
const heroImage = config.hero.image;   // e.g. "assets/imgs/bg7.png"
const heroVideo = config.hero.video;   // e.g. "assets/vid7.mp4"
const siteUrl = (config.site_url || '').replace(/\/+$/, '');

// Hero media block: video with poster + tap-to-play overlay, or a plain image
const heroMediaHtml = config.hero.type === 'image'
  ? `                    <img class="hero-video fade1" src="./${heroImage}" alt="Evento ${escapeHtml(eventName)}" />`
  : `                    <video class="hero-video fade1" autoplay muted loop playsinline webkit-playsinline preload="auto" poster="./${heroImage}" id="hero-bg-video" controlslist="nodownload nofullscreen noremoteplayback" disablepictureinpicture>
                    <source src="./${heroVideo}" type="video/mp4">
                    <img src="./${heroImage}" alt="Evento ${escapeHtml(eventName)}" style="width:100%;height:auto;object-fit:cover;" />
                </video>
                    <!-- Mobile autoplay fallback: shown when autoplay is blocked -->
                    <button id="video-play-overlay" class="video-play-overlay" aria-label="Play video">▶</button>`;

// Optional subtitle line under the title (e.g. "VERO'S BDAY EDITION")
const subtitle = (config.event.subtitle || '').trim();
const subtitleHtml = subtitle
  ? `                <h3 class="hero-subtitle fade2">${escapeHtml(subtitle)}</h3>\n`
  : '';

const values = {
  EVENT_NAME: escapeHtml(eventName),
  EVENT_NAME_UPPER: escapeHtml(eventName.toUpperCase()),
  SEO_TITLE: escapeHtml(eventName),
  SEO_DESCRIPTION: escapeHtml(derived.seoDescription),
  OG_IMAGE_URL: `${siteUrl}/${heroImage}`,
  HERO_IMAGE: heroImage,
  ACCENT_COLOR: config.appearance.accent_color,
  SHORT_DATE: escapeHtml(derived.shortDate),
  DISPLAY_TIME: escapeHtml(derived.displayTime),
  SUBTITLE_HTML: subtitleHtml,
  HERO_MEDIA_HTML: heroMediaHtml
};

// ---------------------------------------------------------------------------
// Render templates
// ---------------------------------------------------------------------------
function render(templateFile, outFile) {
  const templatePath = path.join(ROOT, 'templates', templateFile);
  let html = fs.readFileSync(templatePath, 'utf8');

  html = html.replace(/\{\{([A-Z0-9_]+)\}\}/g, (match, key) => {
    if (!(key in values)) {
      throw new Error(`Unknown template placeholder ${match} in ${templateFile}`);
    }
    return values[key];
  });

  fs.writeFileSync(path.join(ROOT, outFile), html, 'utf8');
  console.log(`  ✔ ${outFile}`);
}

console.log(`Building site for: ${eventName} — ${derived.longDateEs}, ${derived.displayTime}`);
render('index.template.html', 'index.html');
render('success.template.html', 'success.html');

// ---------------------------------------------------------------------------
// generated-config.js — runtime values for script.js (countdown)
// ---------------------------------------------------------------------------
const runtimeConfig = {
  eventName: eventName,
  eventDateTime: derived.isoDateTime,
  countdownEnabled: config.event.countdown_enabled !== false
};
fs.writeFileSync(
  path.join(ROOT, 'generated-config.js'),
  `// GENERATED by build.js from _data/event-config.json — do not edit\n` +
  `window.EVENT_CONFIG = ${JSON.stringify(runtimeConfig, null, 2)};\n`,
  'utf8'
);
console.log('  ✔ generated-config.js');

// ---------------------------------------------------------------------------
// build-info.json — lets the admin dashboard know which config version is live
// ---------------------------------------------------------------------------
const configHash = crypto.createHash('sha256').update(rawConfig).digest('hex').slice(0, 16);
fs.writeFileSync(
  path.join(ROOT, 'build-info.json'),
  JSON.stringify({ configHash, builtAt: new Date().toISOString() }, null, 2) + '\n',
  'utf8'
);
console.log(`  ✔ build-info.json (config ${configHash})`);
console.log('Build complete.');
